[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "livrepl"
version = "0.1.0"
description = "Interpretador de AdvPL independente de AppServer"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
livrepl = "livrepl.main:main"

[tool.setuptools]
packages = ["livrepl"]
package-dir = {livrepl = "."}
